# Generated by Django 4.1.3 on 2022-12-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_func', '0004_rename_shipping_address_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
