# Generated by Django 4.1.3 on 2022-12-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_func', '0006_alter_address_house_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=250),
        ),
    ]
