# Generated by Django 4.1.3 on 2022-12-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('product_price', models.FloatField(default=0, max_length=10)),
                ('product_img_url', models.URLField(max_length=100)),
                ('product_description', models.TextField(max_length=1000)),
                ('product_feature', models.TextField(max_length=1000)),
                ('product_spec', models.TextField(max_length=1000)),
                ('inStock', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('sp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sp_name', models.CharField(max_length=50)),
                ('sp_price', models.FloatField(default=0, max_length=10)),
                ('sp_img_url', models.URLField(max_length=100)),
                ('inStock', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
        ),
    ]
