# Generated by Django 4.1.3 on 2023-01-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
